# default_config:

frontend:

homeassistant:
  debug: true

logger:
  default: warning
  logs:
    custom_components.chuango_alarm: debug
    homeassistant.helpers.update_coordinator: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ::1
